--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekLastPosition
build-by-default: true
branches:
- main
- pm4
projects:
  KygekLastPosition:
    path: ""
    libs:
    - src: KygekTeam/ktpmpl-cfs/ktpmpl-cfs
      version: ^3.0
      branch: pm4-updatenotifier
    lint:
      phpstan: false
...
